/// <reference lib="webworker" />

declare const self: SharedWorkerGlobalScope;
export { };

/**
 * OMNITAB SHARED WORKER
 * 
 * This file runs in a dedicated background thread (SharedWorker) that persists
 * across all tabs of the same origin. It survives page reloads and even
 * outlives all tabs until the last tab closes.
 * 
 * WHY SHAREDWORKER?
 * - Single coordination point for all tabs
 * - Persists state across page reloads
 * - Eliminates duplicate work (one WebSocket, one timer)
 * - Zero latency communication (in-memory, no storage)
 * 
 * @see https://developer.mozilla.org/en-US/docs/Web/API/SharedWorker
 */

// ============================================================================
// TYPE DEFINITIONS
// ============================================================================

/**
 * Represents a connected tab/client
 * Each tab gets a unique ID and maintains its own communication port
 */
interface ConnectedTab {
    /** MessagePort for direct communication with this tab */
    port: MessagePort;
    /** Unique identifier for this tab (generated by client) */
    tabId: string;
    /** When this tab first connected */
    connectedAt: number;
    /** Last heartbeat received (for detecting stale tabs) */
    lastPing: number;
}

/**
 * Structure of messages exchanged between tabs via the worker
 */
interface MessageEnvelope {
    /** Message type (REGISTER, PUBLISH, PING, etc.) */
    type: string;
    /** ID of the tab that sent this message */
    fromTabId: string;
    /** Routing target: all tabs, leader only, or specific tab */
    to?: 'all' | 'leader' | string;
    /** Message payload (event name, data, etc.) */
    data: any;
    /** When message was created (for ordering) */
    timestamp: number;
    /** Unique message ID for deduplication */
    id: string;
}

/**
 * Leader election state
 * The leader tab is responsible for special tasks like WebSocket connections
 */
interface LeaderInfo {
    /** ID of the current leader tab (null if no leader) */
    tabId: string | null;
    /** When this leader was elected */
    electedAt: number | null;
    /** Last heartbeat from leader (to detect stale leadership) */
    lastHeartbeat: number | null;
}

// ============================================================================
// GLOBAL STATE (PERSISTS ACROSS ALL TABS)
// ============================================================================

/**
 * Map of all currently connected tabs
 * This is the source of truth for all active tabs
 * @key tabId - Unique identifier for each tab
 * @value ConnectedTab - Tab information and communication port
 */
const tabs = new Map<string, ConnectedTab>();

/**
 * Current leader information
 * Only one tab can be leader at a time
 * Leader is responsible for privileged operations
 */
let leader: LeaderInfo = {
    tabId: null,
    electedAt: null,
    lastHeartbeat: null
};

/**
 * Message handler registry
 * Maps message types to their handler functions
 * This pattern avoids giant switch statements and makes adding new
 * message types trivial
 */
const handlers: Map<string, (message: MessageEnvelope, sender: ConnectedTab) => void> = new Map();

// ============================================================================
// MESSAGE HANDLERS
// ============================================================================

/**
 * REGISTER: New tab connecting to the worker
 * 
 * Flow:
 * 1. Store tab in tabs Map
 * 2. Send confirmation with current state
 * 3. Notify all other tabs about new arrival
 * 
 * Why registration is required:
 * - Worker needs to know about all tabs
 * - Establishes communication channel
 * - Prevents unauthorized messages
 */
handlers.set('REGISTER', (message, sender) => {
    const { tabId } = message.data;

    // Store tab with its communication port
    tabs.set(tabId, {
        port: sender.port,
        tabId,
        connectedAt: Date.now(),
        lastPing: Date.now() // Initial heartbeat
    });

    console.log(`[SharedWorker] Tab registered: ${tabId}. Total tabs: ${tabs.size}`);

    // Send registration confirmation with current cluster state
    sender.port.postMessage({
        type: 'REGISTERED',
        data: {
            tabId,
            tabCount: tabs.size,
            leader: leader.tabId // Let tab know who the current leader is
        }
    });

    // Notify all existing tabs about the new arrival
    // This enables features like "x users online" counters
    broadcastToAll({
        type: 'TAB_JOINED',
        data: {
            tabId,
            tabCount: tabs.size,
            leader: leader.tabId
        }
    }, tabId);
});

/**
 * PUBLISH: Broadcast an event to all other tabs
 * 
 * This is the core messaging primitive. Any tab can publish an event
 * and all other tabs will receive it.
 * 
 * Use cases:
 * - "user logged out" events
 * - "data updated" notifications
 * - Real-time collaboration
 */
handlers.set('PUBLISH', (message, sender) => {
    const { event, payload } = message.data;

    // Broadcast to all tabs EXCEPT the sender
    // (sender already knows about its own action)
    broadcastToAll({
        type: 'PUBLISH',
        data: {
            event,
            payload,
            fromTabId: sender.tabId // So receivers know who sent it
        }
    }, sender.tabId);
});

/**
 * PING: Heartbeat from tab
 * 
 * Why heartbeats:
 * - Detect tabs that have crashed (not disconnected gracefully)
 * - Clean up stale entries
 * - Maintain accurate tab count
 * 
 * Tabs should send PING every 5-10 seconds
 */
handlers.set('PING', (message, sender) => {
    const tab = tabs.get(sender.tabId);
    if (tab) {
        tab.lastPing = Date.now(); // Update last seen timestamp
    }

    // Respond with PONG to confirm connection is alive
    sender.port.postMessage({
        type: 'PONG',
        data: { timestamp: Date.now() }
    });
});

/**
 * LEADER_ELECTION: Simple leader election protocol
 * 
 * Current algorithm: First tab that asks becomes leader
 * This is intentionally simple for now. Future versions should implement:
 * - Bully algorithm for larger clusters
 * - Raft for consensus
 * - Weighted election based on tab capabilities
 * 
 * Leader responsibilities:
 * - Maintain WebSocket connection
 * - Coordinate background tasks
 * - Cache shared data
 */
handlers.set('LEADER_ELECTION', (message, sender) => {
    const { voteFor } = message.data;

    // Only elect if no leader exists
    if (!leader.tabId) {
        leader = {
            tabId: voteFor || sender.tabId,
            electedAt: Date.now(),
            lastHeartbeat: Date.now()
        };

        // Announce new leader to all tabs
        broadcastToAll({
            type: 'LEADER_ELECTED',
            data: {
                leader: leader.tabId,
                electedAt: leader.electedAt
            }
        });

        console.log(`[SharedWorker] Leader elected: ${leader.tabId}`);
    }
});

/**
 * LEADER_HEARTBEAT: Special heartbeat from leader
 * 
 * Leader sends more frequent heartbeats to prove it's still alive.
 * If leader stops sending heartbeats, other tabs will trigger
 * a new election.
 */
handlers.set('LEADER_HEARTBEAT', (message, sender) => {
    // Only accept heartbeats from the current leader
    if (sender.tabId === leader.tabId) {
        leader.lastHeartbeat = Date.now();
    }
});

/**
 * GET_STATE: Request current cluster state
 * 
 * Useful for newly connected tabs to get:
 * - List of active tabs
 * - Who is the current leader
 * - Cluster statistics
 */
handlers.set('GET_STATE', (message, sender) => {
    sender.port.postMessage({
        type: 'STATE_RESPONSE',
        data: {
            tabs: Array.from(tabs.keys()), // List of tab IDs
            tabCount: tabs.size,
            leader: leader.tabId,
            timestamp: Date.now()
        }
    });
});

/**
 * DISCONNECT: Tab is closing gracefully
 * 
 * Why explicit disconnect matters:
 * - Immediate cleanup (no need to wait for heartbeat timeout)
 * - Accurate tab count for other tabs
 * - Immediate leader re-election if needed
 */
handlers.set('DISCONNECT', (message, sender) => {
    handleTabDisconnect(sender.tabId);
});

// ============================================================================
// CONNECTION HANDLING
// ============================================================================

/**
 * Handle new tab connections
 * 
 * This is the entry point for every new tab. The browser creates a new
 * MessagePort for each connecting tab and passes it here.
 * 
 * @param event - Contains the new port in event.ports[0]
 */
self.onconnect = (event: MessageEvent) => {
    const port = event.ports[0];

    // Set up message handler for this specific tab
    port.onmessage = (event: MessageEvent) => {
        handleMessage(event.data, port);
    };

    // Start the port (required by spec)
    port.start();

    console.log('[SharedWorker] New tab connected, waiting for REGISTER');
};

/**
 * Central message dispatcher
 * 
 * All messages from all tabs flow through here. This function:
 * 1. Validates the tab is registered (except for REGISTER messages)
 * 2. Looks up the appropriate handler
 * 3. Executes the handler with proper context
 * 
 * @param message - Raw message from tab
 * @param port - Communication port to the sending tab
 */
function handleMessage(message: any, port: MessagePort) {
    const { type, tabId, data } = message;

    // Find the tab in our registry
    let tab = tabs.get(tabId);

    // Special case: Unregistered tabs can only send REGISTER
    if (!tab && type !== 'REGISTER') {
        port.postMessage({
            type: 'ERROR',
            data: { message: 'Not registered. Send REGISTER first.' }
        });
        return;
    }

    // For REGISTER messages, create temporary tab entry
    if (!tab) {
        tab = {
            port,
            tabId,
            connectedAt: Date.now(),
            lastPing: Date.now()
        };
    }

    // Dispatch to appropriate handler
    const handler = handlers.get(type);
    if (handler) {
        handler({
            type,
            fromTabId: tabId,
            data,
            timestamp: Date.now(),
            id: crypto.randomUUID() // Unique ID for message tracking
        }, tab);
    } else {
        console.warn(`[SharedWorker] Unknown message type: ${type}`);
    }
}

// ============================================================================
// UTILITY FUNCTIONS
// ============================================================================

/**
 * Broadcast a message to all connected tabs
 * 
 * @param message - Message to broadcast
 * @param excludeTabId - Optional tab to exclude (usually the sender)
 * 
 * Why exclude sender?
 * - Sender already knows about its own action
 * - Prevents echo/feedback loops
 */
function broadcastToAll(message: any, excludeTabId?: string) {
    tabs.forEach((tab, tabId) => {
        if (tabId !== excludeTabId) {
            try {
                tab.port.postMessage(message);
            } catch (e) {
                // If postMessage fails, tab is probably dead
                // Clean it up immediately
                console.warn(`[SharedWorker] Failed to send to ${tabId}, removing`);
                handleTabDisconnect(tabId);
            }
        }
    });
}

/**
 * Handle tab disconnection (graceful or forced)
 * 
 * This function:
 * 1. Removes tab from registry
 * 2. Triggers leader re-election if needed
 * 3. Notifies remaining tabs
 * 
 * @param tabId - ID of disconnected tab
 */
function handleTabDisconnect(tabId: string) {
    const removed = tabs.delete(tabId);

    if (removed) {
        console.log(`[SharedWorker] Tab disconnected: ${tabId}. Remaining: ${tabs.size}`);

        // If leader disconnected, trigger new election
        if (leader.tabId === tabId) {
            console.log('[SharedWorker] Leader disconnected, clearing leader');
            leader = { tabId: null, electedAt: null, lastHeartbeat: null };

            // Only trigger election if other tabs exist
            if (tabs.size > 0) {
                broadcastToAll({
                    type: 'LEADER_ELECTION_NEEDED',
                    data: { reason: 'Leader disconnected' }
                });
            }
        }

        // Notify remaining tabs about the departure
        broadcastToAll({
            type: 'TAB_LEFT',
            data: {
                tabId,
                tabCount: tabs.size,
                leader: leader.tabId
            }
        });
    }
}

// ============================================================================
// MAINTENANCE TASKS
// ============================================================================

/**
 * Periodic cleanup of stale connections
 * 
 * Why this is necessary:
 * - Tabs can crash without sending DISCONNECT
 * - Browser may not notify worker of tab closure
 * - Prevents memory leaks in worker
 * 
 * Runs every 10 seconds
 */
setInterval(() => {
    const now = Date.now();
    const STALE_TIMEOUT = 30000; // 30 seconds without ping = dead

    // Check all tabs for staleness
    tabs.forEach((tab, tabId) => {
        if (now - tab.lastPing > STALE_TIMEOUT) {
            console.log(`[SharedWorker] Tab stale (no ping), removing: ${tabId}`);
            handleTabDisconnect(tabId);
        }
    });

    // Check leader heartbeat
    if (leader.tabId && leader.lastHeartbeat) {
        if (now - leader.lastHeartbeat > STALE_TIMEOUT) {
            console.log('[SharedWorker] Leader stale, triggering re-election');
            leader = { tabId: null, electedAt: null, lastHeartbeat: null };

            if (tabs.size > 0) {
                broadcastToAll({
                    type: 'LEADER_ELECTION_NEEDED',
                    data: { reason: 'Leader heartbeat timeout' }
                });
            }
        }
    }
}, 10000); // Check every 10 seconds

// ============================================================================
// INITIALIZATION
// ============================================================================

console.log('[SharedWorker] Omnitab SharedWorker started');
console.log('[SharedWorker] Ready to coordinate cross-tab communication');